# Code Generated by Sidekick is for learning and experimentation purposes only.
import re
from playwright.sync_api import expect, TimeoutError
from utils.config import PROFILE_NAME, PROFILE_EMAIL


class DashboardPage:
    def __init__(self, page):
        self.page = page

    def dismiss_cookie_popup_if_present(self):
        banner = self.page.locator("#onetrust-banner-sdk, #onetrust-group-container").first

        try:
            banner.wait_for(state="visible", timeout=8000)

            possible_buttons = [
                self.page.locator("#onetrust-reject-all-handler"),
                self.page.locator("#onetrust-close-btn-container button"),
                self.page.get_by_role("button", name=re.compile("cancel", re.I)),
                self.page.get_by_role("button", name=re.compile("reject", re.I)),
                self.page.get_by_role("button", name=re.compile("close", re.I)),
                self.page.locator("button:has-text('Cancel')"),
                self.page.locator("button:has-text('Reject')"),
                self.page.locator("button:has-text('Close')"),
            ]

            for button in possible_buttons:
                try:
                    button.first.wait_for(state="visible", timeout=2000)
                    button.first.click()
                    print("Cookie popup dismissed.")
                    return
                except TimeoutError:
                    pass

            print("Cookie banner found, but no dismiss button matched.")

        except TimeoutError:
            print("Cookie popup not shown.")

    def validate_dashboard_loaded(self):
        expect(self.page.get_by_text("Demand Pursuits", exact=False)).to_be_visible(timeout=15000)

    def validate_categories(self):
        category_section = self.page.locator("section.filter-cards-section").first
        expect(category_section).to_be_visible(timeout=10000)

        cards = category_section.locator(".dna-card-tab")
        expect(cards).to_have_count(6, timeout=10000)

        expected_categories = ["All", "New", "In Progress", "Cancelled", "Won", "Deferred"]
        actual_categories = []

        for i in range(cards.count()):
            card = cards.nth(i)

            category_name = card.locator("span.sc-eeDRCX").inner_text().strip()
            category_count = card.locator("span.sc-jsJBEQ").inner_text().strip()

            actual_categories.append(category_name)

            assert category_name in expected_categories, f"Unexpected category found: {category_name}"
            assert category_count.isdigit(), (
                f"Count is not displayed properly for category '{category_name}': '{category_count}'"
            )

            print(f"Category: {category_name} | Count: {category_count}")

        assert actual_categories == expected_categories, (
            f"Category order mismatch. Expected: {expected_categories}, Actual: {actual_categories}"
        )

    def validate_list_of_pursuits(self):
        pursuits_header = self.page.locator("h3.pursuit-table-title").first
        expect(pursuits_header).to_be_visible(timeout=10000)
        expect(pursuits_header).to_have_text("List of all Pursuits", timeout=10000)
        print("List of all Pursuits is displayed on the Demand Pursuits dashboard.")


    def validate_applications(self):
        applications_button = self.page.get_by_role("button", name="Apps").first

        expect(applications_button).to_be_visible(timeout=10000)
        expect(applications_button).to_be_enabled(timeout=10000)

        print("Applications option is available.")
        applications_button.click(timeout=10000)
        print("Clicked on Applications option.")


    def validate_notifications(self):
        notifications_button = self.page.get_by_role("button", name="Notifications").first

        expect(notifications_button).to_be_visible(timeout=10000)
        expect(notifications_button).to_be_enabled(timeout=10000)

        print("Notifications option is available.")
        notifications_button.click(timeout=10000)
        print("Clicked on Notifications option.")


    def validate_left_pane(self):
        left_pane = self.page.locator("div._menuItemsContainer_1tt27_100").first
        expect(left_pane).to_be_visible(timeout=10000)

        toggle_button = left_pane.locator(
            'button[aria-label="Expand menu"], button[aria-label="Collapse menu"]'
        ).first
        expect(toggle_button).to_be_visible(timeout=10000)
        expect(toggle_button).to_be_enabled(timeout=10000)

        toggle_label = toggle_button.get_attribute("aria-label")
        assert toggle_label in ["Expand menu", "Collapse menu"], \
            f"Unexpected left pane toggle label: {toggle_label}"

        demand_pursuits_button = left_pane.get_by_role("button", name="Demand Pursuits").first
        expect(demand_pursuits_button).to_be_visible(timeout=10000)

        create_pursuit_button = left_pane.get_by_role("button", name="Create Pursuit").first
        expect(create_pursuit_button).to_be_visible(timeout=10000)

        toggle_button.click(timeout=10000)

        if toggle_label == "Expand menu":
            expect(left_pane.get_by_role("button", name="Collapse menu")).to_be_visible(timeout=10000)
        else:
            expect(left_pane.get_by_role("button", name="Expand menu")).to_be_visible(timeout=10000)

    def validate_dashboard(self):
        self.dismiss_cookie_popup_if_present()
        self.validate_dashboard_loaded()
        self.validate_categories()
        self.validate_list_of_pursuits()
      #  self.validate_profile_details()
        self.validate_applications()
        self.validate_notifications()
        self.validate_left_pane()
