# Code Generated by Sidekick is for learning and experimentation purposes only.
import os
from dotenv import load_dotenv

load_dotenv()

BASE_URL = os.getenv("BASE_URL")
USERNAME = os.getenv("DNA_USERNAME")
PASSWORD = os.getenv("DNA_PASSWORD")
PROFILE_NAME = os.getenv("PROFILE_NAME")
PROFILE_EMAIL = os.getenv("PROFILE_EMAIL")
HEADLESS = os.getenv("HEADLESS", "false").lower() == "true"

assert BASE_URL, "BASE_URL is missing in .env"
assert USERNAME, "DNA_USERNAME is missing in .env"
assert PASSWORD, "DNA_PASSWORD is missing in .env"
assert PROFILE_NAME, "PROFILE_NAME is missing in .env"
assert PROFILE_EMAIL, "PROFILE_EMAIL is missing in .env"